.TH "DRAFT\-DODGER" "" "February 2014" "" ""
.SH "NAME"
\fBdraft-dodger\fR
.P
Temporarily add jekyll post drafts to your gitignore
.P
NPM \fIhttps://nodei\.co/npm/draft\-dodger\.png\fR \fIhttps://nodei\.co/npm/draft\-dodger/\fR
.P
 \fIhttp://i\.imgur\.com/anZ7GCd\.png\fR
.RS 0
.IP \(bu 2
\fBnpm install \-g draft\-dodger\fR
.IP \(bu 2
\fBdraftdodger\fR

.RE
.SS Todo
.RS 0
.IP \(bu 2
tests
.IP \(bu 2
add option to list ignored drafts
.IP \(bu 2
add option to unignore a draft

.RE

